"""novo_pedido

Revision ID: 51e92870ce4e
Revises: 161d25292768
Create Date: 2023-07-23 21:28:04.140855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e92870ce4e'
down_revision = '161d25292768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'produto', ['produto_id'], ['id'])

    # ### end Alembic commands ###
